### ISSUE TITLE
ERROR: Tag 6.4.0.1 not found in repository docker.io/ongr/nodejs

### ISSUE THREAD

**Issue by alfredbez** [ongr-io/development-environment#27]
![image](https://cloud.githubusercontent.com/assets/1001186/20888215/2ff31828-bafe-11e6-9e82-30316590dd9a.png)

![image](https://cloud.githubusercontent.com/assets/1001186/20888139/d9fdd732-bafd-11e6-8780-b72c4b06f40a.png) [source](https://hub.docker.com/r/ongr/nodejs/tags/)

Please release 6.4.0.1 or [change it](https://github.com/ongr-io/development-environment/blob/f263e50eaed749c6c5f563c8f1c62584edf5add3/docker-compose.yml#L22) to `6.4.0`

**Comment by saimaz** [comment]
Thank you @alfredbez.
